Feature/serializer
prooph/snapshot-store pull request #7
Opened 2017-04-05 11:02 UTC by basz

2017-04-05 15:42 UTC, prolic requested changes

2017-04-05 15:42 UTC, prolic commented on docs/snapshots.md
> +		'factories' => \Prooph\SnapshotStore\Serializer::class => My\CallbackSerializerFactory::class,
`[` missing

2017-04-05 15:42 UTC, prolic commented on src/CallbackSerializer.php
> +    public function __construct(?callable $serializer, ?callable $deserialize)
use `$unserialize` instead of `$deserialize` please.

2017-04-05 15:42 UTC, prolic commented on src/CallbackSerializer.php
> +    private $deserialize = 'unserialize';
private $unserialize

2017-04-05 15:42 UTC, prolic commented on src/CallbackSerializer.php
> +    private $deserialize = 'unserialize';
or maybe better $unserializeCallback

2017-04-05 15:42 UTC, prolic commented on src/CallbackSerializer.php
> +    public function __construct(?callable $serializer, ?callable $deserialize)
maybe better `?callable $serializeCallback, ?callable $unserializeCallback`

2017-04-05 15:42 UTC, prolic commented on tests/CallbackSerializerTest.php
> +    public function it_both_callback_are_required_before_default_is_not_used(): void
method name: `it_uses_default_if_only_one_callback_provided_instead_of_two`

2017-04-05 21:23 UTC, bweston92 reviewed
Please review my concerns.

2017-04-05 21:23 UTC, bweston92 commented on docs/snapshots.md
> +By default we use php build in serialize/unserialize methods to around aggregate persistence. If you would like to change it you can do that since v1.1.
By default prooph uses PHP's own serialise and unserialize methods. These may not suite your needs so as of v1.1 of the snapshot store you can now use a custom serialiser.

2017-04-05 21:23 UTC, bweston92 commented on src/CallbackSerializer.php
> +        if (null !== $serializeCallback && null !== $unserializeCallback) {
Would it not be better allow custom on either one? For example I might want only want to change something before I serialize. Or I may want to just update a time stamp when I unserialise.

2017-04-05 21:23 UTC, bweston92 commented on src/CallbackSerializer.php
> +        return call_user_func_array($this->serializeCallback, [$data]);
call_user_func_array is for dynamic length arguments. Use call_user_func as it is faster.

Example: return call_user_func($this->serializeCallback, $data);

2017-04-05 21:23 UTC, bweston92 commented on src/CallbackSerializer.php
> +        return call_user_func_array($this->unserializeCallback, [$serialized]);
call_user_func_array is for dynamic length arguments. Use call_user_func as it is faster.

Example: return call_user_func($this->in serializeCallback, $serialized);

2017-04-05 21:24 UTC, bweston92 commented
Good work @basz just a few things to pick up on

2017-04-05 21:32 UTC, basz commented on src/CallbackSerializer.php
> +        if (null !== $serializeCallback && null !== $unserializeCallback) {
don't you think we should discourage such behaviour?

Changing anything on the aggregate should not be done at the snapshot layer... When a snapshot does not exists or isn't up to date events are going to reconstitute it.

This check does not makes it *impossible* but atleast one might be more aware of that. What goes in comes out. Unless i'm missing something?

2017-04-05 21:35 UTC, basz commented on src/CallbackSerializer.php
> +        return call_user_func_array($this->serializeCallback, [$data]);
cool then this should be faster too (not here of course)
```
call_user_func($callable, ...$someArray)
```

2017-04-05 21:41 UTC, bweston92 commented on src/CallbackSerializer.php
> +        if (null !== $serializeCallback && null !== $unserializeCallback) {
Nope you're not missing anything, that is most certainly true it should be in exactly the same state.

2017-04-05 21:43 UTC, bweston92 commented on src/CallbackSerializer.php
> +        return call_user_func_array($this->serializeCallback, [$data]);
Would be an interesting benchmark. I only remember doing it for call_user_func and call_user_func_array without variadic params.

2017-04-06 07:13 UTC, prolic commented on src/CallbackSerializer.php
> +        if (null !== $serializeCallback && null !== $unserializeCallback) {
I am against changing timestamp or anything else within the snapshot. If you want to do some crazy weird stuff, implement your own snapshot-store.

2017-04-06 07:18 UTC, merged